- name: Download Cloud SQL Proxy
  get_url:
    url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
    dest: /usr/local/bin/cloud_sql_proxy
    mode: '0755'

- name: Start Cloud SQL Proxy
  shell: |
    mkdir -p /cloudsql
    nohup cloud_sql_proxy \
      -dir="/cloudsql" \
      -instances="{{ CLOUDSQL_CONNECTION_NAME }}=unix:/cloudsql/gcp-project-terraform-462411:us-central1:bookshelf-sql" \
      > "/var/log/cloud-sql-proxy.log" 2>&1 &








  environment:
    CLOUDSQL_CONNECTION_NAME: "{{ lookup('env', 'CLOUDSQL_CONNECTION_NAME') }}"







#- name: Initialize Cloud SQL tables
#  command: "/home/amanpm108/.pyenv/versions/3.5.10/envs/myenv/bin/python {{ project_dir }}/7-gce/bookshelf/model_cloudsql.py"
#  args:
#    chdir: "{{ project_dir }}"
#  environment:
#    PYTHONPATH: "{{ project_dir }}"
